name = "CellArraysIndexing"
uuid = "6597d73a-e7d2-484e-9044-f54e6a6a1966"
authors = ["Albert de Montserrat <albert.de.montserrat@gmail.com>"]
version = "0.1.0"

[deps]
CellArrays = "d35fcfd7-7af4-4c67-b1aa-d78070614af4"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CellArrays = "0.3"
StaticArrays = "1.9"
julia = "1.9, 1.10, 1.11"
